package cz.martlin.hg6.mrs.diff;

public enum SituationDifference {
	CHANGED_STATUS, //
	CHANGED_REPORT, CHANGED_REPORT_METADATA, CHANGED_REPORT_ITEMS, //
	CHANGED_CONFIG_INTERVAL, CHANGED_CONFIG_RUNNING //
}
