package cz.martlin.hg6.mrs.diff;

public enum SituationDifference {
	@Deprecated CHANGED_STATUS, //
	CHANGED_REPORT, CHANGED_REPORT_METADATA, CHANGED_REPORT_ITEMS, //
	CHANGED_CONFIG_INTERVAL, //
	@Deprecated CHANGED_CONFIG_RUNNING, //
	CHANGED_CORE_STATUS, CHANGED_MRS_STATUS
}
