package cz.martlin.hg6.mrs.diff;

public enum SituationDifference {
	CHANGED_CORE_STATUS, CHANGED_MRS_STATUS, CHANGED_REPORT, //
	CHANGED_REPORT_STOPPED, CHANGED_REPORT_DESC, CHANGED_REPORT_ITEMS, //
	CHANGED_CONFIG_INTERVAL, //

}
